package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BookHistoryAPI service. Represents a row in the &quot;khl_BookHistoryAPI&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.BookHistoryAPIModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.BookHistoryAPIImpl}.
 * </p>
 *
 * @author CSC
 * @see BookHistoryAPI
 * @see fi.csc.avaa.khl.db.model.impl.BookHistoryAPIImpl
 * @see fi.csc.avaa.khl.db.model.impl.BookHistoryAPIModelImpl
 * @generated
 */
public interface BookHistoryAPIModel extends BaseModel<BookHistoryAPI> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a book history a p i model instance should use the {@link BookHistoryAPI} interface instead.
     */

    /**
     * Returns the primary key of this book history a p i.
     *
     * @return the primary key of this book history a p i
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this book history a p i.
     *
     * @param primaryKey the primary key of this book history a p i
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the name of this book history a p i.
     *
     * @return the name of this book history a p i
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this book history a p i.
     *
     * @param name the name of this book history a p i
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.khl.db.model.BookHistoryAPI bookHistoryAPI);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.khl.db.model.BookHistoryAPI> toCacheModel();

    @Override
    public fi.csc.avaa.khl.db.model.BookHistoryAPI toEscapedModel();

    @Override
    public fi.csc.avaa.khl.db.model.BookHistoryAPI toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
