package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Julkaisulajiinfo service. Represents a row in the &quot;julklajiinfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.JulkaisulajiinfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.JulkaisulajiinfoImpl}.
 * </p>
 *
 * @author CSC
 * @see Julkaisulajiinfo
 * @see fi.csc.avaa.khl.db.model.impl.JulkaisulajiinfoImpl
 * @see fi.csc.avaa.khl.db.model.impl.JulkaisulajiinfoModelImpl
 * @generated
 */
public interface JulkaisulajiinfoModel extends BaseModel<Julkaisulajiinfo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a julkaisulajiinfo model instance should use the {@link Julkaisulajiinfo} interface instead.
     */

    /**
     * Returns the primary key of this julkaisulajiinfo.
     *
     * @return the primary key of this julkaisulajiinfo
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this julkaisulajiinfo.
     *
     * @param primaryKey the primary key of this julkaisulajiinfo
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the julklajiid of this julkaisulajiinfo.
     *
     * @return the julklajiid of this julkaisulajiinfo
     */
    public int getJulklajiid();

    /**
     * Sets the julklajiid of this julkaisulajiinfo.
     *
     * @param julklajiid the julklajiid of this julkaisulajiinfo
     */
    public void setJulklajiid(int julklajiid);

    /**
     * Returns the julklaji of this julkaisulajiinfo.
     *
     * @return the julklaji of this julkaisulajiinfo
     */
    @AutoEscape
    public String getJulklaji();

    /**
     * Sets the julklaji of this julkaisulajiinfo.
     *
     * @param julklaji the julklaji of this julkaisulajiinfo
     */
    public void setJulklaji(String julklaji);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        fi.csc.avaa.khl.db.model.Julkaisulajiinfo julkaisulajiinfo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.khl.db.model.Julkaisulajiinfo> toCacheModel();

    @Override
    public fi.csc.avaa.khl.db.model.Julkaisulajiinfo toEscapedModel();

    @Override
    public fi.csc.avaa.khl.db.model.Julkaisulajiinfo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
