package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Kieliinfo service. Represents a row in the &quot;kieliinfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.KieliinfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.KieliinfoImpl}.
 * </p>
 *
 * @author CSC
 * @see Kieliinfo
 * @see fi.csc.avaa.khl.db.model.impl.KieliinfoImpl
 * @see fi.csc.avaa.khl.db.model.impl.KieliinfoModelImpl
 * @generated
 */
public interface KieliinfoModel extends BaseModel<Kieliinfo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a kieliinfo model instance should use the {@link Kieliinfo} interface instead.
     */

    /**
     * Returns the primary key of this kieliinfo.
     *
     * @return the primary key of this kieliinfo
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this kieliinfo.
     *
     * @param primaryKey the primary key of this kieliinfo
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the kieliid of this kieliinfo.
     *
     * @return the kieliid of this kieliinfo
     */
    public int getKieliid();

    /**
     * Sets the kieliid of this kieliinfo.
     *
     * @param kieliid the kieliid of this kieliinfo
     */
    public void setKieliid(int kieliid);

    /**
     * Returns the kieli of this kieliinfo.
     *
     * @return the kieli of this kieliinfo
     */
    @AutoEscape
    public String getKieli();

    /**
     * Sets the kieli of this kieliinfo.
     *
     * @param kieli the kieli of this kieliinfo
     */
    public void setKieli(String kieli);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Kieliinfo kieliinfo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Kieliinfo> toCacheModel();

    @Override
    public Kieliinfo toEscapedModel();

    @Override
    public Kieliinfo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
