package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Kielesta service. Represents a row in the &quot;kielesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.KielestaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.KielestaImpl}.
 * </p>
 *
 * @author CSC
 * @see Kielesta
 * @see fi.csc.avaa.khl.db.model.impl.KielestaImpl
 * @see fi.csc.avaa.khl.db.model.impl.KielestaModelImpl
 * @generated
 */
public interface KielestaModel extends BaseModel<Kielesta> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a kielesta model instance should use the {@link Kielesta} interface instead.
     */

    /**
     * Returns the primary key of this kielesta.
     *
     * @return the primary key of this kielesta
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this kielesta.
     *
     * @param primaryKey the primary key of this kielesta
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the kieliid of this kielesta.
     *
     * @return the kieliid of this kielesta
     */
    public int getKieliid();

    /**
     * Sets the kieliid of this kielesta.
     *
     * @param kieliid the kieliid of this kielesta
     */
    public void setKieliid(int kieliid);

    /**
     * Returns the kieli of this kielesta.
     *
     * @return the kieli of this kielesta
     */
    @AutoEscape
    public String getKieli();

    /**
     * Sets the kieli of this kielesta.
     *
     * @param kieli the kieli of this kielesta
     */
    public void setKieli(String kieli);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.khl.db.model.Kielesta kielesta);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.khl.db.model.Kielesta> toCacheModel();

    @Override
    public fi.csc.avaa.khl.db.model.Kielesta toEscapedModel();

    @Override
    public fi.csc.avaa.khl.db.model.Kielesta toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
