package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Puute service. Represents a row in the &quot;puute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.PuuteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.PuuteImpl}.
 * </p>
 *
 * @author CSC
 * @see Puute
 * @see fi.csc.avaa.khl.db.model.impl.PuuteImpl
 * @see fi.csc.avaa.khl.db.model.impl.PuuteModelImpl
 * @generated
 */
public interface PuuteModel extends BaseModel<Puute> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a puute model instance should use the {@link Puute} interface instead.
     */

    /**
     * Returns the primary key of this puute.
     *
     * @return the primary key of this puute
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this puute.
     *
     * @param primaryKey the primary key of this puute
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the puuteid of this puute.
     *
     * @return the puuteid of this puute
     */
    public int getPuuteid();

    /**
     * Sets the puuteid of this puute.
     *
     * @param puuteid the puuteid of this puute
     */
    public void setPuuteid(int puuteid);

    /**
     * Returns the puutenimi of this puute.
     *
     * @return the puutenimi of this puute
     */
    @AutoEscape
    public String getPuutenimi();

    /**
     * Sets the puutenimi of this puute.
     *
     * @param puutenimi the puutenimi of this puute
     */
    public void setPuutenimi(String puutenimi);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.khl.db.model.Puute puute);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.khl.db.model.Puute> toCacheModel();

    @Override
    public fi.csc.avaa.khl.db.model.Puute toEscapedModel();

    @Override
    public fi.csc.avaa.khl.db.model.Puute toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
