package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Sidottu service. Represents a row in the &quot;sidottu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.SidottuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.SidottuImpl}.
 * </p>
 *
 * @author CSC
 * @see Sidottu
 * @see fi.csc.avaa.khl.db.model.impl.SidottuImpl
 * @see fi.csc.avaa.khl.db.model.impl.SidottuModelImpl
 * @generated
 */
public interface SidottuModel extends BaseModel<Sidottu> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a sidottu model instance should use the {@link Sidottu} interface instead.
     */

    /**
     * Returns the primary key of this sidottu.
     *
     * @return the primary key of this sidottu
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this sidottu.
     *
     * @param primaryKey the primary key of this sidottu
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the sidontaid of this sidottu.
     *
     * @return the sidontaid of this sidottu
     */
    public int getSidontaid();

    /**
     * Sets the sidontaid of this sidottu.
     *
     * @param sidontaid the sidontaid of this sidottu
     */
    public void setSidontaid(int sidontaid);

    /**
     * Returns the sidonta of this sidottu.
     *
     * @return the sidonta of this sidottu
     */
    @AutoEscape
    public String getSidonta();

    /**
     * Sets the sidonta of this sidottu.
     *
     * @param sidonta the sidonta of this sidottu
     */
    public void setSidonta(String sidonta);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Sidottu sidottu);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Sidottu> toCacheModel();

    @Override
    public Sidottu toEscapedModel();

    @Override
    public Sidottu toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
