package fi.csc.avaa.khl.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Teospk service. Represents a row in the &quot;teospk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.khl.db.model.impl.TeospkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.khl.db.model.impl.TeospkImpl}.
 * </p>
 *
 * @author CSC
 * @see Teospk
 * @see fi.csc.avaa.khl.db.model.impl.TeospkImpl
 * @see fi.csc.avaa.khl.db.model.impl.TeospkModelImpl
 * @generated
 */
public interface TeospkModel extends BaseModel<Teospk> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a teospk model instance should use the {@link Teospk} interface instead.
     */

    /**
     * Returns the primary key of this teospk.
     *
     * @return the primary key of this teospk
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this teospk.
     *
     * @param primaryKey the primary key of this teospk
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the teospkid of this teospk.
     *
     * @return the teospkid of this teospk
     */
    public int getTeospkid();

    /**
     * Sets the teospkid of this teospk.
     *
     * @param teospkid the teospkid of this teospk
     */
    public void setTeospkid(int teospkid);

    /**
     * Returns the teospknimi of this teospk.
     *
     * @return the teospknimi of this teospk
     */
    @AutoEscape
    public String getTeospknimi();

    /**
     * Sets the teospknimi of this teospk.
     *
     * @param teospknimi the teospknimi of this teospk
     */
    public void setTeospknimi(String teospknimi);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.khl.db.model.Teospk teospk);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.khl.db.model.Teospk> toCacheModel();

    @Override
    public fi.csc.avaa.khl.db.model.Teospk toEscapedModel();

    @Override
    public fi.csc.avaa.khl.db.model.Teospk toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
