package fi.csc.avaa.khl.db.model.impl;

import fi.csc.avaa.khl.db.model.BookHistoryAPI;

/**
 * The extended model base implementation for the BookHistoryAPI service. Represents a row in the &quot;khl_BookHistoryAPI&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookHistoryAPIImpl}.
 * </p>
 *
 * @author CSC
 * @see BookHistoryAPIImpl
 * @see fi.csc.avaa.khl.db.model.BookHistoryAPI
 * @generated
 */
public abstract class BookHistoryAPIBaseImpl extends BookHistoryAPIModelImpl
    implements BookHistoryAPI {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a book history a p i model instance should use the {@link BookHistoryAPI} interface instead.
     */
}
