package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Kartoituskohde;
import fi.csc.avaa.khl.db.service.KartoituskohdeLocalServiceUtil;

/**
 * The extended model base implementation for the Kartoituskohde service. Represents a row in the &quot;kartoituskohde&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KartoituskohdeImpl}.
 * </p>
 *
 * @author CSC
 * @see KartoituskohdeImpl
 * @see fi.csc.avaa.khl.db.model.Kartoituskohde
 * @generated
 */
public abstract class KartoituskohdeBaseImpl extends KartoituskohdeModelImpl
    implements Kartoituskohde {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kartoituskohde model instance should use the {@link Kartoituskohde} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            KartoituskohdeLocalServiceUtil.addKartoituskohde(this);
        } else {
            KartoituskohdeLocalServiceUtil.updateKartoituskohde(this);
        }
    }
}
