package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.khl.db.model.Kieliinfo;
import fi.csc.avaa.khl.db.model.KieliinfoModel;
import fi.csc.avaa.khl.db.model.KieliinfoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Kieliinfo service. Represents a row in the &quot;kieliinfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.khl.db.model.KieliinfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KieliinfoImpl}.
 * </p>
 *
 * @author CSC
 * @see KieliinfoImpl
 * @see fi.csc.avaa.khl.db.model.Kieliinfo
 * @see fi.csc.avaa.khl.db.model.KieliinfoModel
 * @generated
 */
@JSON(strict = true)
public class KieliinfoModelImpl extends BaseModelImpl<Kieliinfo>
    implements KieliinfoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kieliinfo model instance should use the {@link fi.csc.avaa.khl.db.model.Kieliinfo} interface instead.
     */
    public static final String TABLE_NAME = "kieliinfo";
    public static final Object[][] TABLE_COLUMNS = {
            { "kieliid", Types.INTEGER },
            { "kieli", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table kieliinfo (kieliid INTEGER not null primary key,kieli VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table kieliinfo";
    public static final String ORDER_BY_JPQL = " ORDER BY kieliinfo.kieliid ASC";
    public static final String ORDER_BY_SQL = " ORDER BY kieliinfo.kieliid ASC";
    public static final String DATA_SOURCE = "khl";
    public static final String SESSION_FACTORY = "khlSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.khl.db.model.Kieliinfo"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.khl.db.model.Kieliinfo"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.fi.csc.avaa.khl.db.model.Kieliinfo"),
            true);
    public static long KIELI_COLUMN_BITMASK = 1L;
    public static long KIELIID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.khl.db.model.Kieliinfo"));
    private static ClassLoader _classLoader = Kieliinfo.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Kieliinfo.class
        };
    private int _kieliid;
    private String _kieli;
    private String _originalKieli;
    private long _columnBitmask;
    private Kieliinfo _escapedModel;

    public KieliinfoModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Kieliinfo toModel(KieliinfoSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Kieliinfo model = new KieliinfoImpl();

        model.setKieliid(soapModel.getKieliid());
        model.setKieli(soapModel.getKieli());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Kieliinfo> toModels(KieliinfoSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Kieliinfo> models = new ArrayList<Kieliinfo>(soapModels.length);

        for (KieliinfoSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _kieliid;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setKieliid(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _kieliid;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Kieliinfo.class;
    }

    @Override
    public String getModelClassName() {
        return Kieliinfo.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("kieliid", getKieliid());
        attributes.put("kieli", getKieli());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer kieliid = (Integer) attributes.get("kieliid");

        if (kieliid != null) {
            setKieliid(kieliid);
        }

        String kieli = (String) attributes.get("kieli");

        if (kieli != null) {
            setKieli(kieli);
        }
    }

    @JSON
    @Override
    public int getKieliid() {
        return _kieliid;
    }

    @Override
    public void setKieliid(int kieliid) {
        _kieliid = kieliid;
    }

    @JSON
    @Override
    public String getKieli() {
        if (_kieli == null) {
            return StringPool.BLANK;
        } else {
            return _kieli;
        }
    }

    @Override
    public void setKieli(String kieli) {
        _columnBitmask |= KIELI_COLUMN_BITMASK;

        if (_originalKieli == null) {
            _originalKieli = _kieli;
        }

        _kieli = kieli;
    }

    public String getOriginalKieli() {
        return GetterUtil.getString(_originalKieli);
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public Kieliinfo toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Kieliinfo) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        KieliinfoImpl kieliinfoImpl = new KieliinfoImpl();

        kieliinfoImpl.setKieliid(getKieliid());
        kieliinfoImpl.setKieli(getKieli());

        kieliinfoImpl.resetOriginalValues();

        return kieliinfoImpl;
    }

    @Override
    public int compareTo(Kieliinfo kieliinfo) {
        int primaryKey = kieliinfo.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Kieliinfo)) {
            return false;
        }

        Kieliinfo kieliinfo = (Kieliinfo) obj;

        int primaryKey = kieliinfo.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        KieliinfoModelImpl kieliinfoModelImpl = this;

        kieliinfoModelImpl._originalKieli = kieliinfoModelImpl._kieli;

        kieliinfoModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Kieliinfo> toCacheModel() {
        KieliinfoCacheModel kieliinfoCacheModel = new KieliinfoCacheModel();

        kieliinfoCacheModel.kieliid = getKieliid();

        kieliinfoCacheModel.kieli = getKieli();

        String kieli = kieliinfoCacheModel.kieli;

        if ((kieli != null) && (kieli.length() == 0)) {
            kieliinfoCacheModel.kieli = null;
        }

        return kieliinfoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{kieliid=");
        sb.append(getKieliid());
        sb.append(", kieli=");
        sb.append(getKieli());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.khl.db.model.Kieliinfo");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>kieliid</column-name><column-value><![CDATA[");
        sb.append(getKieliid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kieli</column-name><column-value><![CDATA[");
        sb.append(getKieli());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
