package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Kieliinfo;
import fi.csc.avaa.khl.db.service.KieliinfoLocalServiceUtil;

/**
 * The extended model base implementation for the Kieliinfo service. Represents a row in the &quot;kieliinfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KieliinfoImpl}.
 * </p>
 *
 * @author CSC
 * @see KieliinfoImpl
 * @see fi.csc.avaa.khl.db.model.Kieliinfo
 * @generated
 */
public abstract class KieliinfoBaseImpl extends KieliinfoModelImpl
    implements Kieliinfo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kieliinfo model instance should use the {@link Kieliinfo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            KieliinfoLocalServiceUtil.addKieliinfo(this);
        } else {
            KieliinfoLocalServiceUtil.updateKieliinfo(this);
        }
    }
}
