package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Kielesta;
import fi.csc.avaa.khl.db.service.KielestaLocalServiceUtil;

/**
 * The extended model base implementation for the Kielesta service. Represents a row in the &quot;kielesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KielestaImpl}.
 * </p>
 *
 * @author CSC
 * @see KielestaImpl
 * @see fi.csc.avaa.khl.db.model.Kielesta
 * @generated
 */
public abstract class KielestaBaseImpl extends KielestaModelImpl
    implements Kielesta {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kielesta model instance should use the {@link Kielesta} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            KielestaLocalServiceUtil.addKielesta(this);
        } else {
            KielestaLocalServiceUtil.updateKielesta(this);
        }
    }
}
