package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.khl.db.model.Kuntainfo;
import fi.csc.avaa.khl.db.model.KuntainfoModel;
import fi.csc.avaa.khl.db.model.KuntainfoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Kuntainfo service. Represents a row in the &quot;kuntainfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.khl.db.model.KuntainfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KuntainfoImpl}.
 * </p>
 *
 * @author CSC
 * @see KuntainfoImpl
 * @see fi.csc.avaa.khl.db.model.Kuntainfo
 * @see fi.csc.avaa.khl.db.model.KuntainfoModel
 * @generated
 */
@JSON(strict = true)
public class KuntainfoModelImpl extends BaseModelImpl<Kuntainfo>
    implements KuntainfoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a kuntainfo model instance should use the {@link fi.csc.avaa.khl.db.model.Kuntainfo} interface instead.
     */
    public static final String TABLE_NAME = "kuntainfo";
    public static final Object[][] TABLE_COLUMNS = {
            { "kuntaid", Types.INTEGER },
            { "capitalkuntanimi", Types.VARCHAR },
            { "kpl", Types.INTEGER },
            { "kuntanimi", Types.VARCHAR },
            { "maakuntaid", Types.INTEGER },
            { "kuntano", Types.INTEGER },
            { "kuntanimi_2014", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table kuntainfo (kuntaid INTEGER not null primary key,capitalkuntanimi VARCHAR(75) null,kpl INTEGER,kuntanimi VARCHAR(75) null,maakuntaid INTEGER,kuntano INTEGER,kuntanimi_2014 VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table kuntainfo";
    public static final String ORDER_BY_JPQL = " ORDER BY kuntainfo.kuntaid ASC";
    public static final String ORDER_BY_SQL = " ORDER BY kuntainfo.kuntaid ASC";
    public static final String DATA_SOURCE = "khl";
    public static final String SESSION_FACTORY = "khlSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.khl.db.model.Kuntainfo"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.khl.db.model.Kuntainfo"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.fi.csc.avaa.khl.db.model.Kuntainfo"),
            true);
    public static long CAPITALKUNTANIMI_COLUMN_BITMASK = 1L;
    public static long KUNTAID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.khl.db.model.Kuntainfo"));
    private static ClassLoader _classLoader = Kuntainfo.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Kuntainfo.class
        };
    private int _kuntaid;
    private String _capitalkuntanimi;
    private String _originalCapitalkuntanimi;
    private int _kpl;
    private String _kuntanimi;
    private int _maakuntaid;
    private int _kuntano;
    private String _kuntanimi_2014;
    private long _columnBitmask;
    private Kuntainfo _escapedModel;

    public KuntainfoModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Kuntainfo toModel(KuntainfoSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Kuntainfo model = new KuntainfoImpl();

        model.setKuntaid(soapModel.getKuntaid());
        model.setCapitalkuntanimi(soapModel.getCapitalkuntanimi());
        model.setKpl(soapModel.getKpl());
        model.setKuntanimi(soapModel.getKuntanimi());
        model.setMaakuntaid(soapModel.getMaakuntaid());
        model.setKuntano(soapModel.getKuntano());
        model.setKuntanimi_2014(soapModel.getKuntanimi_2014());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Kuntainfo> toModels(KuntainfoSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Kuntainfo> models = new ArrayList<Kuntainfo>(soapModels.length);

        for (KuntainfoSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _kuntaid;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setKuntaid(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _kuntaid;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Kuntainfo.class;
    }

    @Override
    public String getModelClassName() {
        return Kuntainfo.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("kuntaid", getKuntaid());
        attributes.put("capitalkuntanimi", getCapitalkuntanimi());
        attributes.put("kpl", getKpl());
        attributes.put("kuntanimi", getKuntanimi());
        attributes.put("maakuntaid", getMaakuntaid());
        attributes.put("kuntano", getKuntano());
        attributes.put("kuntanimi_2014", getKuntanimi_2014());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer kuntaid = (Integer) attributes.get("kuntaid");

        if (kuntaid != null) {
            setKuntaid(kuntaid);
        }

        String capitalkuntanimi = (String) attributes.get("capitalkuntanimi");

        if (capitalkuntanimi != null) {
            setCapitalkuntanimi(capitalkuntanimi);
        }

        Integer kpl = (Integer) attributes.get("kpl");

        if (kpl != null) {
            setKpl(kpl);
        }

        String kuntanimi = (String) attributes.get("kuntanimi");

        if (kuntanimi != null) {
            setKuntanimi(kuntanimi);
        }

        Integer maakuntaid = (Integer) attributes.get("maakuntaid");

        if (maakuntaid != null) {
            setMaakuntaid(maakuntaid);
        }

        Integer kuntano = (Integer) attributes.get("kuntano");

        if (kuntano != null) {
            setKuntano(kuntano);
        }

        String kuntanimi_2014 = (String) attributes.get("kuntanimi_2014");

        if (kuntanimi_2014 != null) {
            setKuntanimi_2014(kuntanimi_2014);
        }
    }

    @JSON
    @Override
    public int getKuntaid() {
        return _kuntaid;
    }

    @Override
    public void setKuntaid(int kuntaid) {
        _kuntaid = kuntaid;
    }

    @JSON
    @Override
    public String getCapitalkuntanimi() {
        if (_capitalkuntanimi == null) {
            return StringPool.BLANK;
        } else {
            return _capitalkuntanimi;
        }
    }

    @Override
    public void setCapitalkuntanimi(String capitalkuntanimi) {
        _columnBitmask |= CAPITALKUNTANIMI_COLUMN_BITMASK;

        if (_originalCapitalkuntanimi == null) {
            _originalCapitalkuntanimi = _capitalkuntanimi;
        }

        _capitalkuntanimi = capitalkuntanimi;
    }

    public String getOriginalCapitalkuntanimi() {
        return GetterUtil.getString(_originalCapitalkuntanimi);
    }

    @JSON
    @Override
    public int getKpl() {
        return _kpl;
    }

    @Override
    public void setKpl(int kpl) {
        _kpl = kpl;
    }

    @JSON
    @Override
    public String getKuntanimi() {
        if (_kuntanimi == null) {
            return StringPool.BLANK;
        } else {
            return _kuntanimi;
        }
    }

    @Override
    public void setKuntanimi(String kuntanimi) {
        _kuntanimi = kuntanimi;
    }

    @JSON
    @Override
    public int getMaakuntaid() {
        return _maakuntaid;
    }

    @Override
    public void setMaakuntaid(int maakuntaid) {
        _maakuntaid = maakuntaid;
    }

    @JSON
    @Override
    public int getKuntano() {
        return _kuntano;
    }

    @Override
    public void setKuntano(int kuntano) {
        _kuntano = kuntano;
    }

    @JSON
    @Override
    public String getKuntanimi_2014() {
        if (_kuntanimi_2014 == null) {
            return StringPool.BLANK;
        } else {
            return _kuntanimi_2014;
        }
    }

    @Override
    public void setKuntanimi_2014(String kuntanimi_2014) {
        _kuntanimi_2014 = kuntanimi_2014;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public Kuntainfo toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Kuntainfo) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        KuntainfoImpl kuntainfoImpl = new KuntainfoImpl();

        kuntainfoImpl.setKuntaid(getKuntaid());
        kuntainfoImpl.setCapitalkuntanimi(getCapitalkuntanimi());
        kuntainfoImpl.setKpl(getKpl());
        kuntainfoImpl.setKuntanimi(getKuntanimi());
        kuntainfoImpl.setMaakuntaid(getMaakuntaid());
        kuntainfoImpl.setKuntano(getKuntano());
        kuntainfoImpl.setKuntanimi_2014(getKuntanimi_2014());

        kuntainfoImpl.resetOriginalValues();

        return kuntainfoImpl;
    }

    @Override
    public int compareTo(Kuntainfo kuntainfo) {
        int primaryKey = kuntainfo.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Kuntainfo)) {
            return false;
        }

        Kuntainfo kuntainfo = (Kuntainfo) obj;

        int primaryKey = kuntainfo.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        KuntainfoModelImpl kuntainfoModelImpl = this;

        kuntainfoModelImpl._originalCapitalkuntanimi = kuntainfoModelImpl._capitalkuntanimi;

        kuntainfoModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Kuntainfo> toCacheModel() {
        KuntainfoCacheModel kuntainfoCacheModel = new KuntainfoCacheModel();

        kuntainfoCacheModel.kuntaid = getKuntaid();

        kuntainfoCacheModel.capitalkuntanimi = getCapitalkuntanimi();

        String capitalkuntanimi = kuntainfoCacheModel.capitalkuntanimi;

        if ((capitalkuntanimi != null) && (capitalkuntanimi.length() == 0)) {
            kuntainfoCacheModel.capitalkuntanimi = null;
        }

        kuntainfoCacheModel.kpl = getKpl();

        kuntainfoCacheModel.kuntanimi = getKuntanimi();

        String kuntanimi = kuntainfoCacheModel.kuntanimi;

        if ((kuntanimi != null) && (kuntanimi.length() == 0)) {
            kuntainfoCacheModel.kuntanimi = null;
        }

        kuntainfoCacheModel.maakuntaid = getMaakuntaid();

        kuntainfoCacheModel.kuntano = getKuntano();

        kuntainfoCacheModel.kuntanimi_2014 = getKuntanimi_2014();

        String kuntanimi_2014 = kuntainfoCacheModel.kuntanimi_2014;

        if ((kuntanimi_2014 != null) && (kuntanimi_2014.length() == 0)) {
            kuntainfoCacheModel.kuntanimi_2014 = null;
        }

        return kuntainfoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(15);

        sb.append("{kuntaid=");
        sb.append(getKuntaid());
        sb.append(", capitalkuntanimi=");
        sb.append(getCapitalkuntanimi());
        sb.append(", kpl=");
        sb.append(getKpl());
        sb.append(", kuntanimi=");
        sb.append(getKuntanimi());
        sb.append(", maakuntaid=");
        sb.append(getMaakuntaid());
        sb.append(", kuntano=");
        sb.append(getKuntano());
        sb.append(", kuntanimi_2014=");
        sb.append(getKuntanimi_2014());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(25);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.khl.db.model.Kuntainfo");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>kuntaid</column-name><column-value><![CDATA[");
        sb.append(getKuntaid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>capitalkuntanimi</column-name><column-value><![CDATA[");
        sb.append(getCapitalkuntanimi());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kpl</column-name><column-value><![CDATA[");
        sb.append(getKpl());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kuntanimi</column-name><column-value><![CDATA[");
        sb.append(getKuntanimi());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>maakuntaid</column-name><column-value><![CDATA[");
        sb.append(getMaakuntaid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kuntano</column-name><column-value><![CDATA[");
        sb.append(getKuntano());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kuntanimi_2014</column-name><column-value><![CDATA[");
        sb.append(getKuntanimi_2014());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
