package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Maakuntainfo;
import fi.csc.avaa.khl.db.service.MaakuntainfoLocalServiceUtil;

/**
 * The extended model base implementation for the Maakuntainfo service. Represents a row in the &quot;maakuntainfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MaakuntainfoImpl}.
 * </p>
 *
 * @author CSC
 * @see MaakuntainfoImpl
 * @see fi.csc.avaa.khl.db.model.Maakuntainfo
 * @generated
 */
public abstract class MaakuntainfoBaseImpl extends MaakuntainfoModelImpl
    implements Maakuntainfo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a maakuntainfo model instance should use the {@link Maakuntainfo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MaakuntainfoLocalServiceUtil.addMaakuntainfo(this);
        } else {
            MaakuntainfoLocalServiceUtil.updateMaakuntainfo(this);
        }
    }
}
