package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.khl.db.model.Maakuntainfo;
import fi.csc.avaa.khl.db.model.MaakuntainfoModel;
import fi.csc.avaa.khl.db.model.MaakuntainfoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Maakuntainfo service. Represents a row in the &quot;maakuntainfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.khl.db.model.MaakuntainfoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MaakuntainfoImpl}.
 * </p>
 *
 * @author CSC
 * @see MaakuntainfoImpl
 * @see fi.csc.avaa.khl.db.model.Maakuntainfo
 * @see fi.csc.avaa.khl.db.model.MaakuntainfoModel
 * @generated
 */
@JSON(strict = true)
public class MaakuntainfoModelImpl extends BaseModelImpl<Maakuntainfo>
    implements MaakuntainfoModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a maakuntainfo model instance should use the {@link fi.csc.avaa.khl.db.model.Maakuntainfo} interface instead.
     */
    public static final String TABLE_NAME = "maakuntainfo";
    public static final Object[][] TABLE_COLUMNS = {
            { "maakuntaid", Types.INTEGER },
            { "maakunta", Types.VARCHAR },
            { "kpl", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table maakuntainfo (maakuntaid INTEGER not null primary key,maakunta VARCHAR(75) null,kpl INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table maakuntainfo";
    public static final String ORDER_BY_JPQL = " ORDER BY maakuntainfo.maakuntaid ASC";
    public static final String ORDER_BY_SQL = " ORDER BY maakuntainfo.maakuntaid ASC";
    public static final String DATA_SOURCE = "khl";
    public static final String SESSION_FACTORY = "khlSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.khl.db.model.Maakuntainfo"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.khl.db.model.Maakuntainfo"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.khl.db.model.Maakuntainfo"));
    private static ClassLoader _classLoader = Maakuntainfo.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Maakuntainfo.class
        };
    private int _maakuntaid;
    private String _maakunta;
    private int _kpl;
    private Maakuntainfo _escapedModel;

    public MaakuntainfoModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Maakuntainfo toModel(MaakuntainfoSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Maakuntainfo model = new MaakuntainfoImpl();

        model.setMaakuntaid(soapModel.getMaakuntaid());
        model.setMaakunta(soapModel.getMaakunta());
        model.setKpl(soapModel.getKpl());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Maakuntainfo> toModels(MaakuntainfoSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Maakuntainfo> models = new ArrayList<Maakuntainfo>(soapModels.length);

        for (MaakuntainfoSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _maakuntaid;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setMaakuntaid(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _maakuntaid;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Maakuntainfo.class;
    }

    @Override
    public String getModelClassName() {
        return Maakuntainfo.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("maakuntaid", getMaakuntaid());
        attributes.put("maakunta", getMaakunta());
        attributes.put("kpl", getKpl());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer maakuntaid = (Integer) attributes.get("maakuntaid");

        if (maakuntaid != null) {
            setMaakuntaid(maakuntaid);
        }

        String maakunta = (String) attributes.get("maakunta");

        if (maakunta != null) {
            setMaakunta(maakunta);
        }

        Integer kpl = (Integer) attributes.get("kpl");

        if (kpl != null) {
            setKpl(kpl);
        }
    }

    @JSON
    @Override
    public int getMaakuntaid() {
        return _maakuntaid;
    }

    @Override
    public void setMaakuntaid(int maakuntaid) {
        _maakuntaid = maakuntaid;
    }

    @JSON
    @Override
    public String getMaakunta() {
        if (_maakunta == null) {
            return StringPool.BLANK;
        } else {
            return _maakunta;
        }
    }

    @Override
    public void setMaakunta(String maakunta) {
        _maakunta = maakunta;
    }

    @JSON
    @Override
    public int getKpl() {
        return _kpl;
    }

    @Override
    public void setKpl(int kpl) {
        _kpl = kpl;
    }

    @Override
    public Maakuntainfo toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Maakuntainfo) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        MaakuntainfoImpl maakuntainfoImpl = new MaakuntainfoImpl();

        maakuntainfoImpl.setMaakuntaid(getMaakuntaid());
        maakuntainfoImpl.setMaakunta(getMaakunta());
        maakuntainfoImpl.setKpl(getKpl());

        maakuntainfoImpl.resetOriginalValues();

        return maakuntainfoImpl;
    }

    @Override
    public int compareTo(Maakuntainfo maakuntainfo) {
        int primaryKey = maakuntainfo.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Maakuntainfo)) {
            return false;
        }

        Maakuntainfo maakuntainfo = (Maakuntainfo) obj;

        int primaryKey = maakuntainfo.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<Maakuntainfo> toCacheModel() {
        MaakuntainfoCacheModel maakuntainfoCacheModel = new MaakuntainfoCacheModel();

        maakuntainfoCacheModel.maakuntaid = getMaakuntaid();

        maakuntainfoCacheModel.maakunta = getMaakunta();

        String maakunta = maakuntainfoCacheModel.maakunta;

        if ((maakunta != null) && (maakunta.length() == 0)) {
            maakuntainfoCacheModel.maakunta = null;
        }

        maakuntainfoCacheModel.kpl = getKpl();

        return maakuntainfoCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{maakuntaid=");
        sb.append(getMaakuntaid());
        sb.append(", maakunta=");
        sb.append(getMaakunta());
        sb.append(", kpl=");
        sb.append(getKpl());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.khl.db.model.Maakuntainfo");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>maakuntaid</column-name><column-value><![CDATA[");
        sb.append(getMaakuntaid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>maakunta</column-name><column-value><![CDATA[");
        sb.append(getMaakunta());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>kpl</column-name><column-value><![CDATA[");
        sb.append(getKpl());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
