package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import fi.csc.avaa.khl.db.model.Puute;
import fi.csc.avaa.khl.db.model.PuuteModel;
import fi.csc.avaa.khl.db.model.PuuteSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Puute service. Represents a row in the &quot;puute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link fi.csc.avaa.khl.db.model.PuuteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PuuteImpl}.
 * </p>
 *
 * @author CSC
 * @see PuuteImpl
 * @see fi.csc.avaa.khl.db.model.Puute
 * @see fi.csc.avaa.khl.db.model.PuuteModel
 * @generated
 */
@JSON(strict = true)
public class PuuteModelImpl extends BaseModelImpl<Puute> implements PuuteModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a puute model instance should use the {@link fi.csc.avaa.khl.db.model.Puute} interface instead.
     */
    public static final String TABLE_NAME = "puute";
    public static final Object[][] TABLE_COLUMNS = {
            { "puuteid", Types.INTEGER },
            { "puutenimi", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table puute (puuteid INTEGER not null primary key,puutenimi VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table puute";
    public static final String ORDER_BY_JPQL = " ORDER BY puute.puuteid ASC";
    public static final String ORDER_BY_SQL = " ORDER BY puute.puuteid ASC";
    public static final String DATA_SOURCE = "khl";
    public static final String SESSION_FACTORY = "khlSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.fi.csc.avaa.khl.db.model.Puute"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.fi.csc.avaa.khl.db.model.Puute"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.fi.csc.avaa.khl.db.model.Puute"),
            true);
    public static long PUUTENIMI_COLUMN_BITMASK = 1L;
    public static long PUUTEID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.fi.csc.avaa.khl.db.model.Puute"));
    private static ClassLoader _classLoader = Puute.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Puute.class };
    private int _puuteid;
    private String _puutenimi;
    private String _originalPuutenimi;
    private long _columnBitmask;
    private Puute _escapedModel;

    public PuuteModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Puute toModel(PuuteSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Puute model = new PuuteImpl();

        model.setPuuteid(soapModel.getPuuteid());
        model.setPuutenimi(soapModel.getPuutenimi());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Puute> toModels(PuuteSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Puute> models = new ArrayList<Puute>(soapModels.length);

        for (PuuteSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _puuteid;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setPuuteid(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _puuteid;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Puute.class;
    }

    @Override
    public String getModelClassName() {
        return Puute.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("puuteid", getPuuteid());
        attributes.put("puutenimi", getPuutenimi());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer puuteid = (Integer) attributes.get("puuteid");

        if (puuteid != null) {
            setPuuteid(puuteid);
        }

        String puutenimi = (String) attributes.get("puutenimi");

        if (puutenimi != null) {
            setPuutenimi(puutenimi);
        }
    }

    @JSON
    @Override
    public int getPuuteid() {
        return _puuteid;
    }

    @Override
    public void setPuuteid(int puuteid) {
        _puuteid = puuteid;
    }

    @JSON
    @Override
    public String getPuutenimi() {
        if (_puutenimi == null) {
            return StringPool.BLANK;
        } else {
            return _puutenimi;
        }
    }

    @Override
    public void setPuutenimi(String puutenimi) {
        _columnBitmask |= PUUTENIMI_COLUMN_BITMASK;

        if (_originalPuutenimi == null) {
            _originalPuutenimi = _puutenimi;
        }

        _puutenimi = puutenimi;
    }

    public String getOriginalPuutenimi() {
        return GetterUtil.getString(_originalPuutenimi);
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public Puute toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Puute) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PuuteImpl puuteImpl = new PuuteImpl();

        puuteImpl.setPuuteid(getPuuteid());
        puuteImpl.setPuutenimi(getPuutenimi());

        puuteImpl.resetOriginalValues();

        return puuteImpl;
    }

    @Override
    public int compareTo(Puute puute) {
        int primaryKey = puute.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Puute)) {
            return false;
        }

        Puute puute = (Puute) obj;

        int primaryKey = puute.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PuuteModelImpl puuteModelImpl = this;

        puuteModelImpl._originalPuutenimi = puuteModelImpl._puutenimi;

        puuteModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Puute> toCacheModel() {
        PuuteCacheModel puuteCacheModel = new PuuteCacheModel();

        puuteCacheModel.puuteid = getPuuteid();

        puuteCacheModel.puutenimi = getPuutenimi();

        String puutenimi = puuteCacheModel.puutenimi;

        if ((puutenimi != null) && (puutenimi.length() == 0)) {
            puuteCacheModel.puutenimi = null;
        }

        return puuteCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{puuteid=");
        sb.append(getPuuteid());
        sb.append(", puutenimi=");
        sb.append(getPuutenimi());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("fi.csc.avaa.khl.db.model.Puute");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>puuteid</column-name><column-value><![CDATA[");
        sb.append(getPuuteid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>puutenimi</column-name><column-value><![CDATA[");
        sb.append(getPuutenimi());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
