package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Sidottu;
import fi.csc.avaa.khl.db.service.SidottuLocalServiceUtil;

/**
 * The extended model base implementation for the Sidottu service. Represents a row in the &quot;sidottu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SidottuImpl}.
 * </p>
 *
 * @author CSC
 * @see SidottuImpl
 * @see fi.csc.avaa.khl.db.model.Sidottu
 * @generated
 */
public abstract class SidottuBaseImpl extends SidottuModelImpl
    implements Sidottu {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sidottu model instance should use the {@link Sidottu} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SidottuLocalServiceUtil.addSidottu(this);
        } else {
            SidottuLocalServiceUtil.updateSidottu(this);
        }
    }
}
