package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Teospk;
import fi.csc.avaa.khl.db.service.TeospkLocalServiceUtil;

/**
 * The extended model base implementation for the Teospk service. Represents a row in the &quot;teospk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeospkImpl}.
 * </p>
 *
 * @author CSC
 * @see TeospkImpl
 * @see fi.csc.avaa.khl.db.model.Teospk
 * @generated
 */
public abstract class TeospkBaseImpl extends TeospkModelImpl implements Teospk {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a teospk model instance should use the {@link Teospk} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TeospkLocalServiceUtil.addTeospk(this);
        } else {
            TeospkLocalServiceUtil.updateTeospk(this);
        }
    }
}
