package fi.csc.avaa.khl.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.khl.db.model.Vanhatkirjat;
import fi.csc.avaa.khl.db.service.VanhatkirjatLocalServiceUtil;

/**
 * The extended model base implementation for the Vanhatkirjat service. Represents a row in the &quot;vanhatkirjat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VanhatkirjatImpl}.
 * </p>
 *
 * @author CSC
 * @see VanhatkirjatImpl
 * @see fi.csc.avaa.khl.db.model.Vanhatkirjat
 * @generated
 */
public abstract class VanhatkirjatBaseImpl extends VanhatkirjatModelImpl
    implements Vanhatkirjat {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a vanhatkirjat model instance should use the {@link Vanhatkirjat} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            VanhatkirjatLocalServiceUtil.addVanhatkirjat(this);
        } else {
            VanhatkirjatLocalServiceUtil.updateVanhatkirjat(this);
        }
    }
}
